[MT-54] Login
4Rooms/web pull request #2
Opened 2023-07-12 17:53 UTC by gimmegummies

**Was implemented**:

log in by entering username/email and password;

redirect to the Homepage after login;

storing access and refresh tokens in the Local Storage;

sh*tty logout functionality (removing ONLY access token from the storage).

**Problems**:

The component Header is not updated after login (thus, “login” is not changing to “logout” in the Header after login - you need to refresh the page to get the desired behavior).

2023-07-14 08:35 UTC, delphifeel commented on src/pages/auth/Login/Login.tsx
> +            });
Треба винести в `api` module. Шось типо `api.fetchToken`

2023-07-14 08:36 UTC, delphifeel commented on src/shared/Header/Header.tsx
> +    localStorage.removeItem("accessToken");
Винести в абстракцію. Можно в рамках `api` module теж.

2023-07-14 08:47 UTC, delphifeel requested changes
Коменти залишив

2023-07-18 14:27 UTC, gimmegummies commented
> Коменти залишив

@delphifeel @waridesu подивіться, будь ласка, останні коміти - я вас вірно зрозуміла? можна мерджити?

2023-07-31 19:26 UTC, waridesu approved these changes

2023-07-31 19:27 UTC, merged