Chat Page, without function
4Rooms/web pull request #6
Opened 2023-09-16 13:43 UTC by MacksimBondarew

2023-09-16 18:32 UTC, approximator requested changes
Build doesn't work:

```
/workspace/web (chatPage) $ npm run build

> web@0.0.0 build
> tsc && vite build

src/App.tsx:5:1 - error TS6133: 'Header' is declared but its value is never read.

5 import Header from "./shared/Header/Header";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/App.tsx:5
```

2023-09-16 18:42 UTC, approximator commented on src/pages/Chats/ChatGroup/ChatGroup.tsx
> +import Infrotmation from './Infrotmation/Infrotmation'
Probably a typo here: `Infrotmation`

2023-09-16 21:28 UTC, MacksimBondarew commented on src/pages/Chats/ChatGroup/ChatGroup.tsx
> +import Infrotmation from './Infrotmation/Infrotmation'
I added home in the App

2023-09-19 12:36 UTC, waridesu approved these changes

2023-09-19 14:14 UTC, approximator commented on src/pages/Chats/ChatGroup/ChatGroup.tsx
> +import Infrotmation from './Infrotmation/Infrotmation'
ok, but what does `Infrotmation` mean?

2023-09-19 16:21 UTC, MacksimBondarew commented
с

2023-09-19 16:21 UTC, merged